FROM docker.io/jc21/nginx-proxy-manager:latest

RUN . /opt/certbot/bin/activate \
    && SETUPTOOLS_USE_DISTUTILS=stdlib pip install --no-cache-dir \
        "certbot-dns-cloudflare>=3.0.0" \
    && deactivate

USER root
